name: XKits
version: Build#005
author: Impasta1000
main: com.Impasta1000.XKits.XKits
description: A KitPVP plugin

commands:
    xkits:
        description: Main command
        aliases: [xk]
        
permissions:
    XKits.*:
        description: Gives access to all XKits features
        default: op
        children:
            XKits.Arena.*: true
    
    XKits.Arena.*:
        description: Gives access to all ARENA-related features
        default: false
        children:
            XKits.Arena.SetLobby: true
            XKits.Arena.List: true
            XKits.Arena.DeleteLobby: true
    XKits.Arena.SetLobby:
        description: Set lobby of an arena
        default: false
    XKits.Arena.DeleteLobby:
        description: Delete arena lobby
        default: false
    XKits.Arena.List:
        description: List all arenas in "arenas.yml"
        default: true